# this file is automatically generated by build.py, and it will be included in the dist directory
import load_dependencies

import requests
from wox_plugin import Plugin, Context, PluginInitParams, Query, Result

class KillProcessPlugin(Plugin):
    async def init(self, ctx: Context, params: PluginInitParams) -> None:
        self.api = params.API
        # request the list of running processes
        self.processes = requests.get("https://localhost:5000/api/processes").json()
        
    async def query(self, ctx: Context, query: Query) -> list[Result]:
        return [
            Result(
                Title="Kill Process",
                SubTitle="Kill a process by name",
            )
        ]